# Generated by Django 5.2.9 on 2025-12-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Financial', 'Financial'), ('Product', 'Product')], max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Under Review', 'Under Review'), ('Resolved', 'Resolved')], default='New', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
